export enum Tool {
  Inspect = 'inspect',
  TerraformRaise = 'terraform_raise',
  TerraformLower = 'terraform_lower',
  Water = 'water',
  Tree = 'tree',
  Road = 'road',
  Rail = 'rail',
  PowerLine = 'powerline',
  HydroPlant = 'hydro',
  CoalPlant = 'coal',
  WindTurbine = 'wind',
  SolarFarm = 'solar',
  WaterPump = 'pump',
  WaterTower = 'water_tower',
  WaterPipe = 'water_pipe',
  Residential = 'residential',
  Commercial = 'commercial',
  Industrial = 'industrial',
  Park = 'park',
  Bulldoze = 'bulldoze'
}
