// export_bindings.rs — generates the checked-in TS mirror guest-js needs.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT

//! Regenerates `guest-js/generated/` from `#[derive(TS)]` types: this crate's own
//! `TickEvent` (and everything it structurally depends on — the `Wire*` structs and
//! `SimAlert`/`AlertKind`, all defined in `city-sim-protocol`), plus `Policies` and
//! `CommandResult`, which `guest-js/index.ts` needs for `setPolicies`/`applyTool` but
//! which are not fields of `TickEvent` so `export_all` cannot reach them by walking
//! its dependency graph.
//!
//! **Why a second copy instead of an import into `app/src/game/protocol/generated/`:**
//! `guest-js` is `tauri-plugin-city-sim`'s own npm package (own `package.json`, built
//! standalone with `rollup` — see `crates/tauri-plugin-city-sim/rollup.config.js` and
//! `tsconfig.json`, whose `include` is scoped to `guest-js/*.ts`) and lists only
//! `dist-js`/`guest-js` in its `files` allowlist. `app/` is a *consumer* of this
//! plugin, not a dependency of it — a relative import reaching out of `guest-js/`
//! into `app/src/...` would point the wrong way across that boundary and would
//! silently stop resolving the day this package is ever built or packaged outside
//! this exact monorepo checkout. A second generated directory, driven by the exact
//! same `#[derive(TS)]` types and regenerated by the same `cargo test --workspace`
//! run as `app/src/game/protocol/generated/`, keeps guest-js self-contained without
//! reintroducing hand-mirrored drift — see `crates/city-sim-protocol/tests/export_bindings.rs`
//! for the primary copy.
//!
//! CI enforces freshness with
//! `git diff --exit-code -- crates/tauri-plugin-city-sim/guest-js/generated/` after
//! `cargo test --workspace` — see `.github/workflows/ci.yml`.

use std::path::PathBuf;

use city_sim_protocol::commands::{CommandResult, Policies};
use tauri_plugin_city_sim::commands::TickEvent;
use ts_rs::{Config, TS};

fn export_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("guest-js/generated")
}

#[test]
fn export_bindings() {
    // `TickEvent::tick` (u64) and `::money` (i64) cross the wire as plain JSON
    // numbers (Tauri IPC serialises through serde_json, which has no `bigint`),
    // matching the hand-written mirror this replaces (`tick`/`money` were
    // already documented `number`, with a ±2^53 precision caveat). ts-rs
    // defaults 64-bit integers to `bigint`, which would be a real wire-shape
    // lie here, not just a style choice — override it.
    let cfg = Config::new()
        .with_out_dir(export_dir())
        .with_large_int("number");

    // Pulls in every `Wire*` struct and `SimAlert`/`AlertKind` as structural
    // dependencies of `TickEvent`.
    TickEvent::export_all(&cfg).expect("export TickEvent");
    // Not reachable from `TickEvent`'s own fields — `setPolicies`/`applyTool` use
    // these as standalone command payload/return types.
    Policies::export_all(&cfg).expect("export Policies");
    CommandResult::export_all(&cfg).expect("export CommandResult");
}
