// template_data.rs — single Rust source for the building-template numbers TS renders and charges from.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT

//! `app/src/game/buildings/templateData.json` is generated by
//! [`template_data_fixture_matches_rust_source_of_truth`] below and consumed
//! by `app/src/game/buildings/templates.ts`. Same pattern as
//! `wire_parity.rs`/`app/src/game/protocol/wireParity.json`: on mismatch
//! this prints the JSON the fixture should contain, so regenerating it is a
//! paste, not a rederivation.
//!
//! Every number here used to be hand-copied into TS static template tables
//! (`ZONE_BUILDING_TEMPLATES`/`CIVIC_BUILDING_TEMPLATES`/
//! `POWER_PLANT_TEMPLATES` in `templates.ts`, plus `BUILD_COST` in
//! `constants.ts`) — `buildings.rs`'s `BuildingTemplate` doc comment used to
//! say its values were "taken directly from the TS static template
//! objects", backwards, since nothing on the TS side ever fed back into
//! Rust. This fixture reverses that: Rust is authoritative, TS reads the
//! JSON (`templates.ts`'s numeric fields; `constants.ts`'s `BUILD_COST`).
//!
//! ## Regenerating it
//!
//! A mismatch's panic message already contains the replacement JSON — copy
//! it into `app/src/game/buildings/templateData.json` verbatim.

use std::collections::BTreeMap;

use city_sim_core::buildings::{
    get_building_template, COAL_PLANT_MAINT, COAL_PLANT_MW, HYDRO_PLANT_MAINT, HYDRO_PLANT_MW,
    SOLAR_FARM_MAINT, SOLAR_FARM_MW, WIND_TURBINE_MAINT, WIND_TURBINE_MW,
};
use city_sim_core::commands::tool_cost;
use city_sim_core::state::ServiceKind;
use city_sim_protocol::building_kind::BuildingKind;
use city_sim_protocol::commands::Tool;

const FIXTURE_PATH: &str = "app/src/game/buildings/templateData.json";
const FIXTURE: &str = include_str!("../../../app/src/game/buildings/templateData.json");

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct Footprint {
    width: u32,
    height: u32,
}

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct ServiceSpec {
    radius: u32,
    capacity: u32,
}

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct BuildingTemplateData {
    footprint: Footprint,
    maintenance: f32,
    #[serde(rename = "powerUse")]
    power_use: f32,
    #[serde(rename = "waterUse")]
    water_use: f32,
    #[serde(rename = "waterOutput")]
    water_output: i32,
    #[serde(rename = "populationCapacity")]
    population_capacity: u32,
    #[serde(rename = "jobsCapacity")]
    jobs_capacity: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    service: Option<ServiceSpec>,
    /// A power plant's generation, in MW — `Some` only for the four plant
    /// kinds. The engine consts (`HYDRO_PLANT_MW` &c., `buildings.rs`'s
    /// "Power plant output/maintenance constants" section) are the source;
    /// `constants.ts`'s `POWER_PLANT_CONFIGS.outputMw` reads this instead of
    /// hand-duplicating the four literals.
    #[serde(rename = "outputMw", skip_serializing_if = "Option::is_none")]
    output_mw: Option<u32>,
}

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct TemplateDataFixture {
    buildings: BTreeMap<String, BuildingTemplateData>,
    #[serde(rename = "toolCost")]
    tool_cost: BTreeMap<String, i64>,
}

/// The four power-plant kinds share one static `BuildingTemplate`
/// (`buildings.rs`'s `POWER_PLANT`, whose `maintenance` is a filler value
/// overridden per instance) — their real, per-type upkeep lives in
/// `commands.rs`'s `apply_tool` call sites via these named constants, not in
/// the shared template. See `buildings.rs`'s "Power plant output/maintenance
/// constants" section for why.
fn power_plant_maintenance(kind: BuildingKind) -> f32 {
    match kind {
        BuildingKind::HydroPlant => HYDRO_PLANT_MAINT,
        BuildingKind::CoalPlant => COAL_PLANT_MAINT,
        BuildingKind::WindTurbine => WIND_TURBINE_MAINT,
        BuildingKind::SolarFarm => SOLAR_FARM_MAINT,
        other => unreachable!("{other:?} is not a power plant kind"),
    }
}

fn is_power_plant(kind: BuildingKind) -> bool {
    matches!(
        kind,
        BuildingKind::HydroPlant
            | BuildingKind::CoalPlant
            | BuildingKind::WindTurbine
            | BuildingKind::SolarFarm
    )
}

/// Mirrors `commands.rs`'s `apply_tool` call sites, which pass these same
/// named constants as `place_footprint_building`'s `power_output_mw`.
fn power_plant_output_mw(kind: BuildingKind) -> u32 {
    match kind {
        BuildingKind::HydroPlant => HYDRO_PLANT_MW,
        BuildingKind::CoalPlant => COAL_PLANT_MW,
        BuildingKind::WindTurbine => WIND_TURBINE_MW,
        BuildingKind::SolarFarm => SOLAR_FARM_MW,
        other => unreachable!("{other:?} is not a power plant kind"),
    }
}

fn expected_fixture() -> TemplateDataFixture {
    let mut buildings = BTreeMap::new();
    for &kind in BuildingKind::ALL {
        let tmpl = get_building_template(kind).expect("every BuildingKind has a static template");
        let maintenance = if is_power_plant(kind) {
            power_plant_maintenance(kind)
        } else {
            tmpl.maintenance
        };
        let service = match tmpl.service {
            ServiceKind::None => None,
            ServiceKind::EducationElementary | ServiceKind::EducationHigh => Some(ServiceSpec {
                radius: tmpl.service_coverage,
                capacity: tmpl.service_capacity,
            }),
        };
        let output_mw = is_power_plant(kind).then(|| power_plant_output_mw(kind));
        buildings.insert(
            format!("{kind:?}"),
            BuildingTemplateData {
                footprint: Footprint {
                    width: tmpl.footprint.0,
                    height: tmpl.footprint.1,
                },
                maintenance,
                power_use: tmpl.power_use,
                water_use: tmpl.water_use,
                water_output: tmpl.water_output,
                population_capacity: tmpl.population_capacity,
                jobs_capacity: tmpl.jobs_capacity,
                service,
                output_mw,
            },
        );
    }

    let tool_cost = Tool::ALL
        .iter()
        .map(|&t| (format!("{t:?}"), tool_cost(t)))
        .collect();

    TemplateDataFixture {
        buildings,
        tool_cost,
    }
}

/// Pins the committed TS fixture (`app/src/game/buildings/templateData.json`)
/// against the Rust values it's generated from — a real assertion, not a
/// manual copy-paste step. On mismatch this prints the JSON the fixture
/// should contain, so regenerating it is a paste, not a rederivation.
#[test]
fn template_data_fixture_matches_rust_source_of_truth() {
    let expected = expected_fixture();
    let expected_json = serde_json::to_string_pretty(&expected).unwrap();

    let fixture: TemplateDataFixture = serde_json::from_str(FIXTURE).unwrap_or_else(|e| {
        panic!(
            "{FIXTURE_PATH} failed to parse: {e}\n\n\
             Regenerate it with this content:\n{expected_json}"
        )
    });

    assert_eq!(
        fixture, expected,
        "{FIXTURE_PATH} is out of sync with its Rust source of truth. \
         Regenerate it with this content:\n{expected_json}"
    );
}
