// wire_parity.rs — pins hand-mirrored TS constants/discriminant tables against their Rust source.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT

//! `app/src/game/protocol/wireParity.json` is generated by
//! [`wire_parity_fixture_matches_rust_source_of_truth`] below and consumed by
//! `app/src/game/protocol/wireParity.test.ts`. Same pattern as
//! `occupantParity.json`/`tileKindParity.json`: on mismatch this prints the
//! JSON the fixture should contain, so regenerating it is a paste, not a
//! rederivation.
//!
//! Everything in the fixture is a value some TS file hand-mirrors because
//! it either isn't `ts-rs`-exportable (a `pub const`, not a type — `ts-rs`
//! mirrors types, see `protocol/commands.ts`'s own comment to this effect)
//! or is a discriminant table a bridge maintains its own copy of instead of
//! decoding a wire enum by name (`Tool`, `ViewStratum`, `BuildingStatus`,
//! `BuildingKind`). Lives in `city-sim-core` (not `city-sim-protocol`)
//! because it needs `BuildingStatus` and `WildernessTunables`, both
//! core-only — `city-sim-protocol` cannot depend back on `city-sim-core`.
//!
//! ## Regenerating it
//!
//! A mismatch's panic message already contains the replacement JSON —
//! copy it into `app/src/game/protocol/wireParity.json` verbatim.

use city_sim_core::buildings::BuildingStatus;
use city_sim_core::economy::DAYS_PER_MONTH;
use city_sim_core::wilderness::WildernessTunables;
use city_sim_protocol::building_kind::BuildingKind;
use city_sim_protocol::commands::{
    LightingPolicy, Tool, ViewStratum, MAX_FUNDING, MAX_TAX_RATE, NEUTRAL_TAX_RATE,
};

const FIXTURE_PATH: &str = "app/src/game/protocol/wireParity.json";
const FIXTURE: &str = include_str!("../../../app/src/game/protocol/wireParity.json");

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct NameU8 {
    name: String,
    u8: u8,
}

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct LightingMultiplierTriple {
    power: f32,
    maintenance: f32,
    happiness: f32,
}

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct LightingMultipliers {
    mixed: LightingMultiplierTriple,
    efficient: LightingMultiplierTriple,
    #[serde(rename = "carbonArc")]
    carbon_arc: LightingMultiplierTriple,
}

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct WildernessTuning {
    #[serde(rename = "reserveCostPerDay")]
    reserve_cost_per_day: f32,
    #[serde(rename = "greenIndustrySubsidyPerZone")]
    green_industry_subsidy_per_zone: f32,
    #[serde(rename = "reserveUnlockScore")]
    reserve_unlock_score: f32,
}

#[derive(serde::Serialize, serde::Deserialize, PartialEq, Debug)]
struct WireParityFixture {
    tools: Vec<NameU8>,
    #[serde(rename = "viewStrata")]
    view_strata: Vec<NameU8>,
    #[serde(rename = "buildingStatuses")]
    building_statuses: Vec<NameU8>,
    #[serde(rename = "buildingKinds")]
    building_kinds: Vec<NameU8>,
    #[serde(rename = "daysPerMonth")]
    days_per_month: u32,
    #[serde(rename = "neutralTaxRate")]
    neutral_tax_rate: u8,
    #[serde(rename = "maxTaxRate")]
    max_tax_rate: u8,
    #[serde(rename = "maxFunding")]
    max_funding: u8,
    #[serde(rename = "lightingMultipliers")]
    lighting_multipliers: LightingMultipliers,
    wilderness: WildernessTuning,
}

fn expected_fixture() -> WireParityFixture {
    let wt = WildernessTunables::default();
    WireParityFixture {
        tools: Tool::ALL
            .iter()
            .map(|&t| NameU8 {
                name: format!("{t:?}"),
                u8: t as u8,
            })
            .collect(),
        view_strata: [ViewStratum::Surface, ViewStratum::Underground]
            .iter()
            .map(|&s| NameU8 {
                name: format!("{s:?}"),
                u8: s as u8,
            })
            .collect(),
        building_statuses: BuildingStatus::ALL
            .iter()
            .map(|&s| NameU8 {
                name: format!("{s:?}"),
                u8: s as u8,
            })
            .collect(),
        building_kinds: BuildingKind::ALL
            .iter()
            .map(|&k| NameU8 {
                name: format!("{k:?}"),
                u8: k as u8,
            })
            .collect(),
        days_per_month: DAYS_PER_MONTH,
        neutral_tax_rate: NEUTRAL_TAX_RATE,
        max_tax_rate: MAX_TAX_RATE,
        max_funding: MAX_FUNDING,
        lighting_multipliers: LightingMultipliers {
            mixed: LightingMultiplierTriple {
                power: LightingPolicy::Mixed.power_use_multiplier(),
                maintenance: LightingPolicy::Mixed.maintenance_multiplier(),
                happiness: LightingPolicy::Mixed.happiness_multiplier(),
            },
            efficient: LightingMultiplierTriple {
                power: LightingPolicy::Efficient.power_use_multiplier(),
                maintenance: LightingPolicy::Efficient.maintenance_multiplier(),
                happiness: LightingPolicy::Efficient.happiness_multiplier(),
            },
            carbon_arc: LightingMultiplierTriple {
                power: LightingPolicy::CarbonArc.power_use_multiplier(),
                maintenance: LightingPolicy::CarbonArc.maintenance_multiplier(),
                happiness: LightingPolicy::CarbonArc.happiness_multiplier(),
            },
        },
        wilderness: WildernessTuning {
            reserve_cost_per_day: wt.reserve_cost_per_day,
            green_industry_subsidy_per_zone: wt.green_industry_subsidy_per_zone,
            reserve_unlock_score: wt.reserve_unlock_score,
        },
    }
}

/// Pins the committed TS fixture (`app/src/game/protocol/wireParity.json`)
/// against the Rust values it mirrors — a real assertion, not a manual
/// copy-paste step. On mismatch this prints the JSON the fixture should
/// contain, so regenerating it is a paste, not a rederivation.
#[test]
fn wire_parity_fixture_matches_rust_source_of_truth() {
    let expected = expected_fixture();
    let expected_json = serde_json::to_string_pretty(&expected).unwrap();

    let fixture: WireParityFixture = serde_json::from_str(FIXTURE).unwrap_or_else(|e| {
        panic!(
            "{FIXTURE_PATH} failed to parse: {e}\n\n\
             Regenerate it with this content:\n{expected_json}"
        )
    });

    assert_eq!(
        fixture, expected,
        "{FIXTURE_PATH} is out of sync with its Rust source of truth. \
         Regenerate it with this content:\n{expected_json}"
    );
}
