// templateData.ts — typed loader for the Rust-generated templateData.json.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT
//
// `templateData.json` is generated by `crates/city-sim-core/tests/
// template_data.rs` — see that file's doc comment for the regen flow. It
// carries the engine's own building-template numbers and per-`Tool` build
// costs (`tool_cost`) verbatim; this module just types the JSON import and
// gives call sites named, throwing accessors instead of string-indexing the
// raw object and risking a silent `undefined`.

import raw from './templateData.json';

export interface EngineBuildingData {
  footprint: { width: number; height: number };
  maintenance: number;
  powerUse: number;
  waterUse: number;
  waterOutput: number;
  populationCapacity: number;
  jobsCapacity: number;
  service?: { radius: number; capacity: number };
}

interface TemplateData {
  buildings: Record<string, EngineBuildingData>;
  toolCost: Record<string, number>;
}

const templateData = raw as TemplateData;

/**
 * Look up `kindName`'s engine numbers — keyed by the `BuildingKind` enum's
 * *member name* (`'HydroPlant'`), not its TS string value (`'hydro'`). The
 * JSON is keyed by Rust's `{kind:?}` Debug format, which is spelled
 * identically to the TS `BuildingKind` enum's member names by construction
 * — both alphabets name the same thirteen kinds (see `buildingKind.ts`).
 */
export function engineBuildingData(kindName: string): EngineBuildingData {
  const data = templateData.buildings[kindName];
  if (!data) {
    throw new Error(
      `templateData.json has no "buildings.${kindName}" entry — regenerate it (see crates/city-sim-core/tests/template_data.rs)`
    );
  }
  return data;
}

/**
 * Look up `toolName`'s build cost — keyed by the `Tool` enum's member name
 * (`'HydroPlant'`), matching Rust's `{tool:?}` Debug format the same way
 * `engineBuildingData` does.
 */
export function engineToolCost(toolName: string): number {
  const cost = templateData.toolCost[toolName];
  if (cost === undefined) {
    throw new Error(
      `templateData.json has no "toolCost.${toolName}" entry — regenerate it (see crates/city-sim-core/tests/template_data.rs)`
    );
  }
  return cost;
}
