/**
 * Protocol parity tests — asserts the TS mirror matches the Rust source.
 *
 * The JSON fixture (tileKindParity.json) is generated by:
 *   cargo test -p sim_protocol dump_parity_json -- --nocapture
 *
 * If this test fails after a Rust-side change, regenerate the fixture and
 * update the TS mirror in tileKind.ts accordingly.
 */

import { describe, it, expect } from 'vitest';
import { TileKind } from '../gameState';
import {
  TILE_KIND_BY_U8,
  TILE_KIND_COUNT,
  TILE_KIND_TO_U8,
  tileKindFromU8,
  tileKindToU8,
} from './tileKind';
import { BYTES_PER_TILE, STATUS, tileBufferOffsets, decodeHappiness, encodeHappiness, decodeEco, encodeEco, ECO_RANGE, decodeScore, decodeTileBuffer } from './tileBuffer';
import { ServiceId, createTileServiceState } from '../services';
import { Terrain, ZoneDensity } from './occupants';
import type { Tile } from '../gameState';
import { LEGACY_BYTES_PER_TILE, LEGACY_FLAGS, legacyTileBufferOffsets } from './legacyTileBuffer';
import parityFixture from './tileKindParity.json';

// ---------------------------------------------------------------------------
// TileKind parity
// ---------------------------------------------------------------------------

describe('protocol: TileKind ↔ u8 parity with Rust', () => {
  it('fixture entry count matches TILE_KIND_COUNT', () => {
    expect(parityFixture.length).toBe(TILE_KIND_COUNT);
  });

  it('every fixture entry matches the TS mapping', () => {
    for (const { u8, ts } of parityFixture) {
      const kind = tileKindFromU8(u8);
      expect(kind, `u8 ${u8} should map to TileKind`).toBeDefined();
      expect(kind, `u8 ${u8} → expected '${ts}', got '${kind}'`).toBe(ts as TileKind);
      expect(tileKindToU8(kind!), `TileKind '${ts}' → u8 should be ${u8}`).toBe(u8);
    }
  });

  it('no duplicate u8 values', () => {
    const seen = new Set<number>();
    for (const [, u8] of TILE_KIND_TO_U8) {
      expect(seen.has(u8), `duplicate u8 ${u8}`).toBe(false);
      seen.add(u8);
    }
  });

  it('u8 range is contiguous starting at 0', () => {
    const values = [...TILE_KIND_TO_U8.values()].sort((a, b) => a - b);
    values.forEach((v, i) => expect(v).toBe(i));
  });

  it('TILE_KIND_BY_U8 length matches count', () => {
    expect(TILE_KIND_BY_U8.length).toBe(TILE_KIND_COUNT);
  });

  it('round-trips all TileKind values', () => {
    for (const kind of Object.values(TileKind)) {
      const u8 = tileKindToU8(kind);
      expect(tileKindFromU8(u8)).toBe(kind);
    }
  });
});

// ---------------------------------------------------------------------------
// Tile buffer layout
// ---------------------------------------------------------------------------

describe('protocol: tile buffer layout', () => {
  it('BYTES_PER_TILE is 11', () => expect(BYTES_PER_TILE).toBe(11));

  it('offsets for 64×64 map', () => {
    const n = 64 * 64;
    const off = tileBufferOffsets(n);
    expect(off.underground).toBe(0);
    expect(off.surface).toBe(4096);
    expect(off.overhead).toBe(8192);
    expect(off.status).toBe(12288);
    expect(off.happiness).toBe(16384);
    expect(off.elevation).toBe(20480);
    expect(off.buildingId).toBe(24576);
    expect(off.wilderness).toBe(32768);
    expect(off.elementaryScore).toBe(36864);
    expect(off.highScore).toBe(40960);
  });

  it('STATUS bitmask values (excluding the density field) are unique powers of 2', () => {
    const vals = [
      STATUS.POWERED,
      STATUS.WATERED,
      STATUS.ABANDONED,
      STATUS.WATER_TERRAIN,
      STATUS.ELEMENTARY_SERVED,
      STATUS.HIGH_SERVED
    ];
    const unique = new Set(vals);
    expect(unique.size).toBe(vals.length);
    for (const v of vals) {
      expect(v & (v - 1)).toBe(0); // power of 2
    }
  });

  it('happiness encode/decode round-trips', () => {
    for (const h of [0, 0.5, 1.0, 1.5, 2.0]) {
      expect(Math.abs(decodeHappiness(encodeHappiness(h)) - h)).toBeLessThan(0.01);
    }
  });

  it('eco encode/decode round-trips and matches the Rust neutral centre', () => {
    for (const e of [-10, -5, -1, 0, 1, 5, 10]) {
      expect(Math.abs(decodeEco(encodeEco(e)) - e)).toBeLessThan(0.1);
    }
    expect(encodeEco(0)).toBe(128);
    expect(encodeEco(999)).toBe(encodeEco(ECO_RANGE));
    expect(encodeEco(-999)).toBe(encodeEco(-ECO_RANGE));
  });

  it('education score decodes the [0, 1] range from a u8', () => {
    expect(decodeScore(0)).toBe(0);
    expect(decodeScore(255)).toBe(1);
    expect(Math.abs(decodeScore(128) - 0.5)).toBeLessThan(0.01);
  });

  it('decodeTileBuffer sets per-tile education served/scores from the status bits and score bytes', () => {
    const n = 2;
    const makeTile = (): Tile => ({
      elevation: 0,
      happiness: 1,
      powered: false,
      watered: false,
      services: createTileServiceState(),
      terrain: Terrain.Land,
      underground: 0,
      surface: 0,
      overhead: 0,
      density: ZoneDensity.Low
    });
    const tiles = [makeTile(), makeTile()];
    const o = tileBufferOffsets(n);
    const bytes = new Array(n * BYTES_PER_TILE).fill(0);
    bytes[o.status + 0] = STATUS.ELEMENTARY_SERVED;
    bytes[o.status + 1] = STATUS.HIGH_SERVED;
    bytes[o.elementaryScore + 0] = 255;
    bytes[o.highScore + 1] = 128;

    decodeTileBuffer(tiles, bytes);

    expect(tiles[0].services.served[ServiceId.EducationElementary]).toBe(true);
    expect(tiles[0].services.served[ServiceId.EducationHigh]).toBe(false);
    expect(tiles[0].services.scores[ServiceId.EducationElementary]).toBe(1);

    expect(tiles[1].services.served[ServiceId.EducationElementary]).toBe(false);
    expect(tiles[1].services.served[ServiceId.EducationHigh]).toBe(true);
    expect(Math.abs(tiles[1].services.scores[ServiceId.EducationHigh]! - 0.5)).toBeLessThan(0.01);
  });
});

describe('protocol: frozen legacy tile buffer layout', () => {
  it('LEGACY_BYTES_PER_TILE is 8', () => expect(LEGACY_BYTES_PER_TILE).toBe(8));

  it('offsets for 64×64 map', () => {
    const n = 64 * 64;
    const off = legacyTileBufferOffsets(n);
    expect(off.kind).toBe(0);
    expect(off.flags).toBe(4096);
    expect(off.happiness).toBe(8192);
    expect(off.elevation).toBe(12288);
    expect(off.buildingId).toBe(16384);
    expect(off.undergroundKind).toBe(24576);
    expect(off.wilderness).toBe(28672);
  });

  it('LEGACY_FLAGS bitmask values are unique powers of 2', () => {
    const vals = Object.values(LEGACY_FLAGS);
    const unique = new Set(vals);
    expect(unique.size).toBe(vals.length);
    for (const v of vals) {
      expect(v & (v - 1)).toBe(0); // power of 2
    }
  });
});
