/**
 * Protocol parity tests — asserts the TS mirror matches the Rust source.
 *
 * The JSON fixture (tileKindParity.json) is generated by:
 *   cargo test -p sim_protocol dump_parity_json -- --nocapture
 *
 * If this test fails after a Rust-side change, regenerate the fixture and
 * update the TS mirror in tileKind.ts accordingly.
 */

import { describe, it, expect } from 'vitest';
import { TileKind } from '../gameState';
import {
  TILE_KIND_BY_U8,
  TILE_KIND_COUNT,
  TILE_KIND_TO_U8,
  tileKindFromU8,
  tileKindToU8,
} from './tileKind';
import { BYTES_PER_TILE, FLAGS, tileBufferOffsets, decodeHappiness, encodeHappiness } from './tileBuffer';
import parityFixture from './tileKindParity.json';

// ---------------------------------------------------------------------------
// TileKind parity
// ---------------------------------------------------------------------------

describe('protocol: TileKind ↔ u8 parity with Rust', () => {
  it('fixture entry count matches TILE_KIND_COUNT', () => {
    expect(parityFixture.length).toBe(TILE_KIND_COUNT);
  });

  it('every fixture entry matches the TS mapping', () => {
    for (const { u8, ts } of parityFixture) {
      const kind = tileKindFromU8(u8);
      expect(kind, `u8 ${u8} should map to TileKind`).toBeDefined();
      expect(kind, `u8 ${u8} → expected '${ts}', got '${kind}'`).toBe(ts as TileKind);
      expect(tileKindToU8(kind!), `TileKind '${ts}' → u8 should be ${u8}`).toBe(u8);
    }
  });

  it('no duplicate u8 values', () => {
    const seen = new Set<number>();
    for (const [, u8] of TILE_KIND_TO_U8) {
      expect(seen.has(u8), `duplicate u8 ${u8}`).toBe(false);
      seen.add(u8);
    }
  });

  it('u8 range is contiguous starting at 0', () => {
    const values = [...TILE_KIND_TO_U8.values()].sort((a, b) => a - b);
    values.forEach((v, i) => expect(v).toBe(i));
  });

  it('TILE_KIND_BY_U8 length matches count', () => {
    expect(TILE_KIND_BY_U8.length).toBe(TILE_KIND_COUNT);
  });

  it('round-trips all TileKind values', () => {
    for (const kind of Object.values(TileKind)) {
      const u8 = tileKindToU8(kind);
      expect(tileKindFromU8(u8)).toBe(kind);
    }
  });
});

// ---------------------------------------------------------------------------
// Tile buffer layout
// ---------------------------------------------------------------------------

describe('protocol: tile buffer layout', () => {
  it('BYTES_PER_TILE is 7', () => expect(BYTES_PER_TILE).toBe(7));

  it('offsets for 64×64 map', () => {
    const n = 64 * 64;
    const off = tileBufferOffsets(n);
    expect(off.kind).toBe(0);
    expect(off.flags).toBe(4096);
    expect(off.happiness).toBe(8192);
    expect(off.elevation).toBe(12288);
    expect(off.buildingId).toBe(16384);
    expect(off.undergroundKind).toBe(24576);
  });

  it('FLAGS bitmask values are unique powers of 2', () => {
    const vals = Object.values(FLAGS);
    const unique = new Set(vals);
    expect(unique.size).toBe(vals.length);
    for (const v of vals) {
      expect(v & (v - 1)).toBe(0); // power of 2
    }
  });

  it('happiness encode/decode round-trips', () => {
    for (const h of [0, 0.5, 1.0, 1.5, 2.0]) {
      expect(Math.abs(decodeHappiness(encodeHappiness(h)) - h)).toBeLessThan(0.01);
    }
  });
});
