/**
 * TileKind ↔ u8 wire mapping — TS mirror of crates/sim_protocol/src/tile_kind.rs.
 *
 * These values are serialised in the SharedArrayBuffer tile mirror and in
 * command-log replays. Do not change them without updating the Rust source
 * and re-committing tileKindParity.json (generated by `cargo test dump_parity_json`).
 *
 * The `TileKind` string values here match `src/game/gameState.ts` TileKind enum.
 */

import { TileKind } from '../gameState';

/** Stable u8 → TileKind lookup (index = u8 value). */
export const TILE_KIND_BY_U8: ReadonlyArray<TileKind> = [
  TileKind.Land,             // 0
  TileKind.Water,            // 1
  TileKind.Tree,             // 2
  TileKind.Road,             // 3
  TileKind.Rail,             // 4
  TileKind.Residential,      // 5
  TileKind.Commercial,       // 6
  TileKind.Industrial,       // 7
  TileKind.PowerLine,        // 8
  TileKind.HydroPlant,       // 9
  TileKind.WaterPump,        // 10
  TileKind.WaterTower,       // 11
  TileKind.WaterPipe,        // 12
  TileKind.ElementarySchool, // 13
  TileKind.HighSchool,       // 14
  TileKind.Park,             // 15
  TileKind.CoalPlant,        // 16
  TileKind.WindTurbine,      // 17
  TileKind.SolarFarm,        // 18
];

/** TileKind string → u8. */
export const TILE_KIND_TO_U8: ReadonlyMap<TileKind, number> = new Map(
  TILE_KIND_BY_U8.map((kind, u8) => [kind, u8])
);

/** Total number of tile kinds — must match `TileKind::ALL.len()` in Rust. */
export const TILE_KIND_COUNT = 19;

export function tileKindFromU8(u8: number): TileKind | undefined {
  return TILE_KIND_BY_U8[u8];
}

export function tileKindToU8(kind: TileKind): number {
  const v = TILE_KIND_TO_U8.get(kind);
  if (v === undefined) throw new Error(`Unknown TileKind: ${kind}`);
  return v;
}
