// wireParity.test.ts — pins every hand-mirrored TS constant/discriminant table against wireParity.json.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT

/**
 * `wireParity.json` is generated by
 * `wire_parity::wire_parity_fixture_matches_rust_source_of_truth`
 * (`crates/city-sim-core/tests/wire_parity.rs`) — same pattern as
 * `tileKindParity.json`/`occupantParity.json`. Everything asserted here is a
 * value some TS file hand-mirrors because it either isn't `ts-rs`-exportable
 * (a Rust `pub const`, not a type) or is a discriminant table a bridge keeps
 * its own copy of rather than decoding a wire enum by name.
 */

import { describe, it, expect } from 'vitest';
import { Tool } from '../toolTypes';
import type { ViewStratum } from '../gameState';
import { TOOL_TO_U8, STRATUM_TO_U8 } from '../wasmSimBridge';
import { BuildingStatus } from '../buildings/state';
import { BUILDING_STATUS_TABLE } from './buildingStatus';
import { BuildingKind } from '../buildings/templates';
import { BUILDING_KIND_BY_U8, BUILDING_KIND_TO_U8, BUILDING_KIND_COUNT } from './buildingKind';
import { DAYS_PER_MONTH } from '../time';
import { NEUTRAL_TAX_RATE, MAX_TAX_RATE, MAX_FUNDING, NATURE_RESERVE_UNLOCK_SCORE } from './commands';
import {
  LIGHTING_POLICIES,
  NATURE_RESERVE_COST_PER_DAY,
  GREEN_INDUSTRY_SUBSIDY_PER_ZONE
} from '../bylaws';
import wireParityFixture from './wireParity.json';

interface NameU8 {
  name: string;
  u8: number;
}

interface WireParityFixture {
  tools: NameU8[];
  viewStrata: NameU8[];
  buildingStatuses: NameU8[];
  buildingKinds: NameU8[];
  daysPerMonth: number;
  neutralTaxRate: number;
  maxTaxRate: number;
  maxFunding: number;
  lightingMultipliers: {
    mixed: { power: number; maintenance: number; happiness: number };
    efficient: { power: number; maintenance: number; happiness: number };
    carbonArc: { power: number; maintenance: number; happiness: number };
  };
  wilderness: {
    reserveCostPerDay: number;
    greenIndustrySubsidyPerZone: number;
    reserveUnlockScore: number;
  };
}

const fixture = wireParityFixture as WireParityFixture;

describe('wireParity: Tool ↔ u8', () => {
  it('every fixture entry matches TOOL_TO_U8, in Rust discriminant order', () => {
    fixture.tools.forEach(({ name, u8 }) => {
      const tool = Tool[name as keyof typeof Tool];
      expect(tool, `Tool.${name} should exist`).toBeDefined();
      expect(TOOL_TO_U8[tool], `TOOL_TO_U8[Tool.${name}]`).toBe(u8);
    });
  });

  it('fixture count matches TOOL_TO_U8 size', () => {
    expect(fixture.tools.length).toBe(Object.keys(TOOL_TO_U8).length);
  });
});

describe('wireParity: ViewStratum ↔ u8', () => {
  const NAMES: Record<ViewStratum, string> = { surface: 'Surface', underground: 'Underground' };

  it('every fixture entry matches STRATUM_TO_U8', () => {
    (Object.keys(STRATUM_TO_U8) as ViewStratum[]).forEach((stratum) => {
      const entry = fixture.viewStrata.find((e) => e.name === NAMES[stratum]);
      expect(entry, `wireParity.json should have a "${NAMES[stratum]}" entry`).toBeDefined();
      expect(STRATUM_TO_U8[stratum]).toBe(entry!.u8);
    });
  });

  it('fixture count matches STRATUM_TO_U8 size', () => {
    expect(fixture.viewStrata.length).toBe(Object.keys(STRATUM_TO_U8).length);
  });
});

describe('wireParity: BuildingStatus ↔ u8', () => {
  it('every fixture entry matches BUILDING_STATUS_TABLE, in Rust discriminant order', () => {
    fixture.buildingStatuses.forEach(({ name, u8 }, i) => {
      const status = BuildingStatus[name as keyof typeof BuildingStatus];
      expect(status, `BuildingStatus.${name} should exist`).toBeDefined();
      expect(BUILDING_STATUS_TABLE[i], `BUILDING_STATUS_TABLE[${u8}]`).toBe(status);
    });
  });

  it('fixture count matches BUILDING_STATUS_TABLE length', () => {
    expect(fixture.buildingStatuses.length).toBe(BUILDING_STATUS_TABLE.length);
  });
});

describe('wireParity: BuildingKind ↔ u8', () => {
  it('every fixture entry matches BUILDING_KIND_BY_U8/BUILDING_KIND_TO_U8', () => {
    fixture.buildingKinds.forEach(({ name, u8 }) => {
      const kind = BuildingKind[name as keyof typeof BuildingKind];
      expect(kind, `BuildingKind.${name} should exist`).toBeDefined();
      expect(BUILDING_KIND_BY_U8.get(u8), `BUILDING_KIND_BY_U8.get(${u8})`).toBe(kind);
      expect(BUILDING_KIND_TO_U8.get(kind), `BUILDING_KIND_TO_U8.get(BuildingKind.${name})`).toBe(u8);
    });
  });

  it('fixture count matches BUILDING_KIND_COUNT', () => {
    expect(fixture.buildingKinds.length).toBe(BUILDING_KIND_COUNT);
  });
});

describe('wireParity: scalar constants', () => {
  it('DAYS_PER_MONTH', () => {
    expect(DAYS_PER_MONTH).toBe(fixture.daysPerMonth);
  });

  it('NEUTRAL_TAX_RATE / MAX_TAX_RATE / MAX_FUNDING', () => {
    expect(NEUTRAL_TAX_RATE).toBe(fixture.neutralTaxRate);
    expect(MAX_TAX_RATE).toBe(fixture.maxTaxRate);
    expect(MAX_FUNDING).toBe(fixture.maxFunding);
  });

  it('NATURE_RESERVE_UNLOCK_SCORE', () => {
    expect(NATURE_RESERVE_UNLOCK_SCORE).toBe(fixture.wilderness.reserveUnlockScore);
  });

  it('bylaws.ts wilderness programme pricing', () => {
    expect(NATURE_RESERVE_COST_PER_DAY).toBe(fixture.wilderness.reserveCostPerDay);
    expect(GREEN_INDUSTRY_SUBSIDY_PER_ZONE).toBe(fixture.wilderness.greenIndustrySubsidyPerZone);
  });
});

describe('wireParity: LightingPolicy multipliers (bylaws.ts)', () => {
  it('mixed / efficient / carbonArc all match LIGHTING_POLICIES', () => {
    const cases: [keyof typeof LIGHTING_POLICIES, keyof WireParityFixture['lightingMultipliers']][] = [
      ['mixed', 'mixed'],
      ['efficient', 'efficient'],
      ['carbonArc', 'carbonArc']
    ];
    for (const [policyId, fixtureKey] of cases) {
      const def = LIGHTING_POLICIES[policyId];
      const want = fixture.lightingMultipliers[fixtureKey];
      expect(def.powerUseMultiplier, `${policyId}.powerUseMultiplier`).toBe(want.power);
      expect(def.maintenanceMultiplier, `${policyId}.maintenanceMultiplier`).toBe(want.maintenance);
      expect(def.happinessMultiplier, `${policyId}.happinessMultiplier`).toBe(want.happiness);
    }
  });
});
