// Web Worker that hosts the WASM SimHost for the WasmSimBridge.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT

/**
 * wasmSim.worker.ts — Web Worker that owns the WASM SimHost.
 *
 * Protocol (both directions use structured-clone via postMessage): see the
 * `MainToWorker` and worker-response shapes below — they are the source of
 * truth. Undo/redo restore full engine snapshots (stroke-level, session-only);
 * every response that can change undo/redo availability carries
 * `history: HistoryFlags`.
 */
// Generated by wasm-pack; run `bun run build:wasm` to regenerate.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import init, { SimHost, version as engineVersion, build_sha as engineSha } from '../wasm/sim_wasm/sim_wasm.js';
import wasmUrl from '../wasm/sim_wasm/sim_wasm_bg.wasm?url';

/** Mirrors `city_sim_protocol::events::SimAlert` — see `take_alerts_json()`. */
export interface SimAlertWire {
  kind: 'PowerDeficit' | 'PowerRestored' | 'WaterDeficit' | 'WaterRestored' | 'BudgetWarning' | 'Abandonment' | 'Info';
  message: string;
  sticky: boolean;
}

export interface SimStats {
  tick: number;
  day: number;
  money: number;
  population: number;
  jobs: number;
  powerBalance: number;
  powerProduced: number;
  powerUsed: number;
  waterBalance: number;
  waterProduced: number;
  waterUsed: number;
  demandResidential: number;
  demandCommercial: number;
  demandIndustrial: number;
  budgetNetPerDay: number;
  budgetNetPerMonth: number;
  budgetRevenue: number;
  budgetExpenses: number;
  budgetRevenueBase: number;
  budgetRevenuePop: number;
  budgetRevenueCommercial: number;
  budgetRevenueIndustrial: number;
  budgetExpensesTransport: number;
  budgetExpensesBuildings: number;
  budgetMaintPower: number;
  budgetMaintCivic: number;
  budgetMaintZones: number;
  budgetMaintRoads: number;
  budgetMaintRail: number;
  budgetMaintPowerLines: number;
  budgetMaintPipes: number;
  budgetMaintPowerHydro: number;
  budgetMaintPowerCoal: number;
  budgetMaintPowerWind: number;
  budgetMaintPowerSolar: number;
  budgetMaintCivicPark: number;
  budgetMaintCivicPump: number;
  budgetMaintCivicTower: number;
  budgetMaintCivicSchool: number;
  budgetMaintZonesRes: number;
  budgetMaintZonesCom: number;
  budgetMaintZonesInd: number;
  budgetRevenueTourism: number;
  budgetExpensesPolicies: number;
  wildernessScore: number;
  wildernessTrend: number;
  wildernessForests: number;
  wildernessParks: number;
  wildernessOpenLand: number;
  wildernessWaterEdge: number;
  wildernessPatch: number;
  wildernessFragmentation: number;
  wildernessZones: number;
  wildernessIndustry: number;
  wildernessTransport: number;
  wildernessPower: number;
  wildernessCivic: number;
}

/**
 * Every player-adjustable policy family — structural mirror of `Policies` in
 * `city-sim-protocol` (camelCase). Passed to `SimHost.set_policies` as JSON so
 * new families cross the boundary without new host methods.
 */
export interface WorkerPolicies {
  budget: {
    taxResidential: number;
    taxCommercial: number;
    taxIndustrial: number;
    fundTransport: number;
    fundPower: number;
    fundCivic: number;
  };
  wilderness: {
    natureReserve: boolean;
    greenIndustry: boolean;
  };
}

/** One-time legacy JSON-save import — see `city_sim_core::import`. */
export interface LegacyEngineImport {
  width: number;
  height: number;
  seed: number;
  /** xoshiro128** state words from the save's `rngState`. */
  rngState: [number, number, number, number];
  /** Wire-layout SoA tile buffer re-encoded from the saved TS tiles. */
  tiles: Uint8Array;
  money: number;
  day: number;
  tick: number;
  population: number;
  jobs: number;
  policies: WorkerPolicies;
}

type MainToWorker =
  | { type: 'init';          payload: { width: number; height: number; seed: number; terrain?: Uint8Array; policies?: WorkerPolicies } }
  | { type: 'apply_tool';    payload: { tool: number; x: number; y: number; strokeId: number } }
  | { type: 'set_speed';     payload: { multiplier: number } }
  | { type: 'set_policies';  payload: WorkerPolicies }
  | { type: 'undo' }
  | { type: 'redo' }
  | { type: 'new_city';      payload: { requestId: number; width: number; height: number; seed: number; terrain?: Uint8Array } }
  | { type: 'get_snapshot';  payload: { requestId: number } }
  | { type: 'load_snapshot'; payload: { requestId: number; bytes: Uint8Array } }
  | { type: 'import_legacy'; payload: { requestId: number } & LegacyEngineImport };

function applyPolicies(h: SimHost, p: WorkerPolicies) {
  h.set_policies(JSON.stringify(p));
}

/** Undo/redo availability, attached to every response that can change it. */
export interface HistoryFlags {
  canUndo: boolean;
  canRedo: boolean;
}

function historyFlags(h: SimHost): HistoryFlags {
  return { canUndo: h.can_undo(), canRedo: h.can_redo() };
}

let host: SimHost | null = null;

// ---------------------------------------------------------------------------
// Worker-driven step clock
// ---------------------------------------------------------------------------
//
// The worker owns the simulation clock (mirroring the Tauri plugin's native
// 20 Hz thread) instead of being stepped from the main thread's rAF loop.
// Worker timers are not throttled in hidden tabs, so the city keeps running
// in the background — and returning to the tab never triggers a fast-forward
// "catch-up rush", because there is nothing to catch up on.

const STEP_INTERVAL_MS = 50;
// Longest real-time gap fed into one step. Timer delays beyond this (OS
// sleep, mobile tab suspension) are dropped rather than fast-forwarded —
// the sim simply loses that wall-clock time.
const MAX_STEP_DT_S = 2;

let stepTimer: ReturnType<typeof setInterval> | null = null;
let lastStepAt = 0;

// Bumped every time `apply_tool` runs (see the 'apply_tool' case below).
// `apply_tool` mutates tiles directly and is NOT gated by the speed-scaled
// tick accumulator (a tool placed while paused changes the tile buffer
// without bumping tick_count) — WasmSimBridge stamps every step_result/
// undo_result/redo_result/load_result with the current value of this counter
// so it can tell "buffer identical to what I already applied" (same tick AND
// same mutationSeq) apart from "a tool was placed since, tick just hasn't
// moved because we're paused" (same tick, different mutationSeq). Bumping it
// synchronously inside the single-threaded worker means any step_result
// gathered after an apply_tool call is guaranteed to carry the post-mutation
// value — no ack/race window, unlike a main-thread "did I just send a
// command" flag (which can't tell a stale in-flight step_result apart from
// a fresh post-mutation one).
let mutationSeq = 0;

function startStepLoop(): void {
  if (stepTimer !== null) return;
  lastStepAt = performance.now();
  stepTimer = setInterval(() => {
    if (!host) return;
    const now = performance.now();
    const dt = Math.min((now - lastStepAt) / 1000, MAX_STEP_DT_S);
    lastStepAt = now;
    host.step(dt);
    const bytes = host.tile_buffer();
    const stats = gatherStats(host);
    const buildingsJson = host.buildings_json();
    const alerts: SimAlertWire[] = JSON.parse(host.take_alerts_json() || '[]');
    self.postMessage(
      { type: 'step_result', bytes, stats, buildingsJson, mutationSeq, alerts },
      { transfer: [bytes.buffer as ArrayBuffer] },
    );
  }, STEP_INTERVAL_MS);
}

function gatherStats(h: SimHost): SimStats {
  return {
    tick:                    h.tick_count(),
    day:                     h.day(),
    money:                   h.money(),
    population:              h.population(),
    jobs:                    h.jobs(),
    powerBalance:            h.power_balance(),
    powerProduced:           h.power_produced(),
    powerUsed:               h.power_used(),
    waterBalance:            h.water_balance(),
    waterProduced:           h.water_produced(),
    waterUsed:               h.water_used(),
    demandResidential:       h.demand_residential(),
    demandCommercial:        h.demand_commercial(),
    demandIndustrial:        h.demand_industrial(),
    budgetNetPerDay:         h.budget_net_per_day(),
    budgetNetPerMonth:       h.budget_net_per_month(),
    budgetRevenue:           h.budget_revenue(),
    budgetExpenses:          h.budget_expenses(),
    budgetRevenueBase:       h.budget_revenue_base(),
    budgetRevenuePop:        h.budget_revenue_pop(),
    budgetRevenueCommercial: h.budget_revenue_commercial(),
    budgetRevenueIndustrial: h.budget_revenue_industrial(),
    budgetExpensesTransport: h.budget_expenses_transport(),
    budgetExpensesBuildings: h.budget_expenses_buildings(),
    budgetMaintPower:        h.budget_maint_power(),
    budgetMaintCivic:        h.budget_maint_civic(),
    budgetMaintZones:        h.budget_maint_zones(),
    budgetMaintRoads:        h.budget_maint_roads(),
    budgetMaintRail:         h.budget_maint_rail(),
    budgetMaintPowerLines:   h.budget_maint_power_lines(),
    budgetMaintPipes:        h.budget_maint_pipes(),
    budgetMaintPowerHydro:   h.budget_maint_power_hydro(),
    budgetMaintPowerCoal:    h.budget_maint_power_coal(),
    budgetMaintPowerWind:    h.budget_maint_power_wind(),
    budgetMaintPowerSolar:   h.budget_maint_power_solar(),
    budgetMaintCivicPark:    h.budget_maint_civic_park(),
    budgetMaintCivicPump:    h.budget_maint_civic_pump(),
    budgetMaintCivicTower:   h.budget_maint_civic_tower(),
    budgetMaintCivicSchool:  h.budget_maint_civic_school(),
    budgetMaintZonesRes:     h.budget_maint_zones_res(),
    budgetMaintZonesCom:     h.budget_maint_zones_com(),
    budgetMaintZonesInd:     h.budget_maint_zones_ind(),
    budgetRevenueTourism:    h.budget_revenue_tourism(),
    budgetExpensesPolicies:  h.budget_expenses_policies(),
    wildernessScore:         h.wilderness_score(),
    wildernessTrend:         h.wilderness_trend(),
    wildernessForests:       h.wilderness_forests(),
    wildernessParks:         h.wilderness_parks(),
    wildernessOpenLand:      h.wilderness_open_land(),
    wildernessWaterEdge:     h.wilderness_water_edge(),
    wildernessPatch:         h.wilderness_patch(),
    wildernessFragmentation: h.wilderness_fragmentation(),
    wildernessZones:         h.wilderness_zones(),
    wildernessIndustry:      h.wilderness_industry(),
    wildernessTransport:     h.wilderness_transport(),
    wildernessPower:         h.wilderness_power(),
    wildernessCivic:         h.wilderness_civic(),
  };
}

/**
 * `Last-Modified` of the WASM this worker actually loaded.
 *
 * A `HEAD` rather than a re-fetch: the body is a quarter of a megabyte and
 * already instantiated, and only the header is wanted. `cache: 'no-store'` so
 * the answer describes the file on the server right now — which is the whole
 * point, since comparing it against page-load time is what reveals that the
 * running module is older than the one on disk.
 *
 * Never throws: this is diagnostics, and a boot must not fail because a header
 * was unavailable.
 */
async function wasmLastModified(): Promise<string | null> {
  try {
    const res = await fetch(wasmUrl, { method: 'HEAD', cache: 'no-store' });
    const lm = res.headers.get('last-modified');
    return lm ? new Date(lm).toISOString() : null;
  } catch {
    return null;
  }
}

/**
 * Interval between re-checks of the WASM's `Last-Modified`.
 *
 * Sampling once at boot is useless, which was the first version of this: the
 * page always loads *after* the binary it loaded, so a single reading can only
 * ever say "not stale". The whole point is to notice the file changing
 * underneath a page that is already running — a rebuild during development, or
 * a deploy landing under a long-open tab — and that can only be seen by asking
 * again.
 *
 * 30 s is chosen against what it costs: a `HEAD` with no body, on a file the
 * browser already holds, against the origin that is already serving the app.
 * Fast enough that a rebuild is flagged before you have finished wondering why
 * your change did nothing.
 */
const WASM_FRESHNESS_INTERVAL_MS = 30_000;

/**
 * Re-check the WASM's timestamp, telling the main thread only when it moves.
 *
 * Deliberately not wired into the 20 Hz step loop: this is a network round trip
 * and belongs on its own slow clock. It also never posts unchanged values, so a
 * quiet page is a silent one.
 */
function startFreshnessWatch(initial: string | null): void {
  let seen = initial;
  setInterval(() => {
    void wasmLastModified().then((lm) => {
      if (lm && lm !== seen) {
        seen = lm;
        self.postMessage({ type: 'build_update', build: { lastModified: lm } });
      }
    });
  }, WASM_FRESHNESS_INTERVAL_MS);
}

self.onmessage = async (e: MessageEvent<MainToWorker>) => {
  const msg = e.data;
  switch (msg.type) {
    case 'init': {
      // Nothing has booted yet if this throws (unsupported WASM feature,
      // fetch failure, out of memory on a constrained device) — surface it
      // rather than leaving the main thread waiting for a 'ready' that will
      // never arrive.
      try {
        await init();
        host = new SimHost(msg.payload.width, msg.payload.height, msg.payload.seed);
        // Terrain must land before the first step so placement validation and
        // wilderness see the real water/tree map. Saves are NOT loaded through
        // init — the bridge follows up with 'load_snapshot'/'import_legacy'.
        if (msg.payload.terrain) host.set_natural_terrain(msg.payload.terrain);
        if (msg.payload.policies) applyPolicies(host, msg.payload.policies);
        // Posting 'ready' must be the last statement in this block — once the
        // main thread has been told we're up, nothing after this may throw
        // into the catch below, or it would post 'init_error' for a boot that
        // already succeeded.
        startStepLoop();
        const lastModified = await wasmLastModified();
        startFreshnessWatch(lastModified);
        self.postMessage({
          type: 'ready',
          history: historyFlags(host),
          build: { version: engineVersion(), sha: engineSha(), lastModified }
        });
      } catch (err) {
        self.postMessage({ type: 'init_error', message: err instanceof Error ? err.message : String(err) });
      }
      break;
    }
    case 'apply_tool': {
      if (!host) break;
      const success = host.apply_tool(msg.payload.tool, msg.payload.x, msg.payload.y, msg.payload.strokeId);
      const message = host.last_apply_message() ?? null;
      // Bump unconditionally (not just on success) — cheap, and keeps this
      // simple; a rejected placement just costs one extra harmless apply on
      // the main thread instead of a missed one.
      mutationSeq++;
      self.postMessage({ type: 'apply_result', success, message, history: historyFlags(host) });
      break;
    }
    case 'set_speed': {
      if (!host) break;
      host.set_speed(msg.payload.multiplier);
      break;
    }
    case 'set_policies': {
      if (!host) break;
      applyPolicies(host, msg.payload);
      break;
    }
    case 'undo': {
      if (!host) break;
      const happened = host.undo();
      if (happened) {
        const bytes = host.tile_buffer();
        const stats = gatherStats(host);
        const buildingsJson = host.buildings_json();
        self.postMessage(
          { type: 'undo_result', happened: true, bytes, stats, buildingsJson, mutationSeq, history: historyFlags(host) },
          { transfer: [bytes.buffer as ArrayBuffer] },
        );
      } else {
        self.postMessage({ type: 'undo_result', happened: false, history: historyFlags(host) });
      }
      break;
    }
    case 'redo': {
      if (!host) break;
      const happened = host.redo();
      if (happened) {
        const bytes = host.tile_buffer();
        const stats = gatherStats(host);
        const buildingsJson = host.buildings_json();
        self.postMessage(
          { type: 'redo_result', happened: true, bytes, stats, buildingsJson, mutationSeq, history: historyFlags(host) },
          { transfer: [bytes.buffer as ArrayBuffer] },
        );
      } else {
        self.postMessage({ type: 'redo_result', happened: false, history: historyFlags(host) });
      }
      break;
    }
    case 'new_city': {
      // Fresh city on a new seed (MCP debug reset / future New Game flow).
      host = new SimHost(msg.payload.width, msg.payload.height, msg.payload.seed);
      if (msg.payload.terrain) host.set_natural_terrain(msg.payload.terrain);
      postLoadResult(host, msg.payload.requestId);
      break;
    }
    case 'get_snapshot': {
      if (!host) break;
      const bytes = host.get_snapshot();
      self.postMessage(
        { type: 'snapshot_result', requestId: msg.payload.requestId, bytes },
        { transfer: [bytes.buffer as ArrayBuffer] },
      );
      break;
    }
    case 'load_snapshot': {
      if (!host) break;
      try {
        host.load_snapshot(msg.payload.bytes);
      } catch (err) {
        self.postMessage({ type: 'load_result', requestId: msg.payload.requestId, ok: false, error: String(err) });
        break;
      }
      postLoadResult(host, msg.payload.requestId);
      break;
    }
    case 'import_legacy': {
      if (!host) break;
      const p = msg.payload;
      try {
        host.import_legacy(
          p.width, p.height, p.seed,
          new Uint32Array(p.rngState), p.tiles,
          p.money, p.day, p.tick, p.population, p.jobs,
          JSON.stringify(p.policies),
        );
      } catch (err) {
        self.postMessage({ type: 'load_result', requestId: p.requestId, ok: false, error: String(err) });
        break;
      }
      postLoadResult(host, p.requestId);
      break;
    }
  }
};

/** Push the full post-load state back to the bridge in one message. */
function postLoadResult(h: SimHost, requestId: number): void {
  const bytes = h.tile_buffer();
  self.postMessage(
    {
      type: 'load_result',
      requestId,
      ok: true,
      width: h.width(),
      height: h.height(),
      seed: h.seed(),
      policies: JSON.parse(h.policies_json()) as WorkerPolicies,
      bytes,
      stats: gatherStats(h),
      buildingsJson: h.buildings_json(),
      mutationSeq,
      history: historyFlags(h),
    },
    { transfer: [bytes.buffer as ArrayBuffer] },
  );
}
