// Web Worker that hosts the WASM SimHost for the WasmSimBridge.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT

/**
 * wasmSim.worker.ts — Web Worker that owns the WASM SimHost.
 *
 * Protocol (both directions use structured-clone via postMessage): see the
 * `MainToWorker` and worker-response shapes below — they are the source of
 * truth. Undo/redo restore full engine snapshots (stroke-level, session-only);
 * every response that can change undo/redo availability carries
 * `history: HistoryFlags`.
 */
// Generated by wasm-pack; run `bun run build:wasm` to regenerate.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import init, { SimHost } from '../wasm/sim_wasm/sim_wasm.js';

export interface SimStats {
  tick: number;
  day: number;
  money: number;
  population: number;
  jobs: number;
  powerBalance: number;
  powerProduced: number;
  powerUsed: number;
  waterBalance: number;
  waterProduced: number;
  waterUsed: number;
  demandResidential: number;
  demandCommercial: number;
  demandIndustrial: number;
  budgetNetPerDay: number;
  budgetNetPerMonth: number;
  budgetRevenue: number;
  budgetExpenses: number;
  budgetRevenueBase: number;
  budgetRevenuePop: number;
  budgetRevenueCommercial: number;
  budgetRevenueIndustrial: number;
  budgetExpensesTransport: number;
  budgetExpensesBuildings: number;
  budgetMaintPower: number;
  budgetMaintCivic: number;
  budgetMaintZones: number;
  budgetMaintRoads: number;
  budgetMaintRail: number;
  budgetMaintPowerLines: number;
  budgetMaintPipes: number;
  budgetMaintPowerHydro: number;
  budgetMaintPowerCoal: number;
  budgetMaintPowerWind: number;
  budgetMaintPowerSolar: number;
  budgetMaintCivicPark: number;
  budgetMaintCivicPump: number;
  budgetMaintCivicTower: number;
  budgetMaintCivicSchool: number;
  budgetMaintZonesRes: number;
  budgetMaintZonesCom: number;
  budgetMaintZonesInd: number;
  budgetRevenueTourism: number;
  budgetExpensesPolicies: number;
  wildernessScore: number;
  wildernessTrend: number;
  wildernessForests: number;
  wildernessParks: number;
  wildernessOpenLand: number;
  wildernessWaterEdge: number;
  wildernessPatch: number;
  wildernessFragmentation: number;
  wildernessZones: number;
  wildernessIndustry: number;
  wildernessTransport: number;
  wildernessPower: number;
  wildernessCivic: number;
}

/**
 * Every player-adjustable policy family — structural mirror of `Policies` in
 * `city-sim-protocol` (camelCase). Passed to `SimHost.set_policies` as JSON so
 * new families cross the boundary without new host methods.
 */
export interface WorkerPolicies {
  budget: {
    taxResidential: number;
    taxCommercial: number;
    taxIndustrial: number;
    fundTransport: number;
    fundPower: number;
    fundCivic: number;
  };
  wilderness: {
    natureReserve: boolean;
    greenIndustry: boolean;
  };
}

type MainToWorker =
  | { type: 'init';       payload: { width: number; height: number; seed: number; terrain?: Uint8Array; commands?: { tool: number; x: number; y: number }[]; money?: number; targetTick?: number; policies?: WorkerPolicies } }
  | { type: 'step';       payload: { dt: number } }
  | { type: 'apply_tool'; payload: { tool: number; x: number; y: number; strokeId: number } }
  | { type: 'set_speed';  payload: { multiplier: number } }
  | { type: 'set_policies'; payload: WorkerPolicies }
  | { type: 'undo' }
  | { type: 'redo' }
  | { type: 'reset';      payload: { width: number; height: number; seed: number; terrain?: Uint8Array } }
  | { type: 'load';       payload: { width: number; height: number; seed: number; terrain?: Uint8Array; commands?: { tool: number; x: number; y: number }[]; money?: number; targetTick?: number; policies?: WorkerPolicies } };

function applyPolicies(h: SimHost, p: WorkerPolicies) {
  h.set_policies(JSON.stringify(p));
}

/** Undo/redo availability, attached to every response that can change it. */
export interface HistoryFlags {
  canUndo: boolean;
  canRedo: boolean;
}

function historyFlags(h: SimHost): HistoryFlags {
  return { canUndo: h.can_undo(), canRedo: h.can_redo() };
}

let host: SimHost | null = null;

function gatherStats(h: SimHost): SimStats {
  return {
    tick:                    h.tick_count(),
    day:                     h.day(),
    money:                   h.money(),
    population:              h.population(),
    jobs:                    h.jobs(),
    powerBalance:            h.power_balance(),
    powerProduced:           h.power_produced(),
    powerUsed:               h.power_used(),
    waterBalance:            h.water_balance(),
    waterProduced:           h.water_produced(),
    waterUsed:               h.water_used(),
    demandResidential:       h.demand_residential(),
    demandCommercial:        h.demand_commercial(),
    demandIndustrial:        h.demand_industrial(),
    budgetNetPerDay:         h.budget_net_per_day(),
    budgetNetPerMonth:       h.budget_net_per_month(),
    budgetRevenue:           h.budget_revenue(),
    budgetExpenses:          h.budget_expenses(),
    budgetRevenueBase:       h.budget_revenue_base(),
    budgetRevenuePop:        h.budget_revenue_pop(),
    budgetRevenueCommercial: h.budget_revenue_commercial(),
    budgetRevenueIndustrial: h.budget_revenue_industrial(),
    budgetExpensesTransport: h.budget_expenses_transport(),
    budgetExpensesBuildings: h.budget_expenses_buildings(),
    budgetMaintPower:        h.budget_maint_power(),
    budgetMaintCivic:        h.budget_maint_civic(),
    budgetMaintZones:        h.budget_maint_zones(),
    budgetMaintRoads:        h.budget_maint_roads(),
    budgetMaintRail:         h.budget_maint_rail(),
    budgetMaintPowerLines:   h.budget_maint_power_lines(),
    budgetMaintPipes:        h.budget_maint_pipes(),
    budgetMaintPowerHydro:   h.budget_maint_power_hydro(),
    budgetMaintPowerCoal:    h.budget_maint_power_coal(),
    budgetMaintPowerWind:    h.budget_maint_power_wind(),
    budgetMaintPowerSolar:   h.budget_maint_power_solar(),
    budgetMaintCivicPark:    h.budget_maint_civic_park(),
    budgetMaintCivicPump:    h.budget_maint_civic_pump(),
    budgetMaintCivicTower:   h.budget_maint_civic_tower(),
    budgetMaintCivicSchool:  h.budget_maint_civic_school(),
    budgetMaintZonesRes:     h.budget_maint_zones_res(),
    budgetMaintZonesCom:     h.budget_maint_zones_com(),
    budgetMaintZonesInd:     h.budget_maint_zones_ind(),
    budgetRevenueTourism:    h.budget_revenue_tourism(),
    budgetExpensesPolicies:  h.budget_expenses_policies(),
    wildernessScore:         h.wilderness_score(),
    wildernessTrend:         h.wilderness_trend(),
    wildernessForests:       h.wilderness_forests(),
    wildernessParks:         h.wilderness_parks(),
    wildernessOpenLand:      h.wilderness_open_land(),
    wildernessWaterEdge:     h.wilderness_water_edge(),
    wildernessPatch:         h.wilderness_patch(),
    wildernessFragmentation: h.wilderness_fragmentation(),
    wildernessZones:         h.wilderness_zones(),
    wildernessIndustry:      h.wilderness_industry(),
    wildernessTransport:     h.wilderness_transport(),
    wildernessPower:         h.wilderness_power(),
    wildernessCivic:         h.wilderness_civic(),
  };
}

self.onmessage = async (e: MessageEvent<MainToWorker>) => {
  const msg = e.data;
  switch (msg.type) {
    case 'init': {
      await init();
      host = new SimHost(msg.payload.width, msg.payload.height, msg.payload.seed);
      // Terrain must land before commands so placement validation sees the
      // real water/tree map, and before the first step so wilderness does.
      if (msg.payload.terrain) host.set_natural_terrain(msg.payload.terrain);
      if (msg.payload.policies) applyPolicies(host, msg.payload.policies);
      if (msg.payload.commands) {
        for (const cmd of msg.payload.commands) {
          host.apply_tool(cmd.tool, cmd.x, cmd.y, 0);
        }
        // Fast-forward enough for zone buildings to spawn (growth delay ≈ 40
        // ticks). Cap at 120 so we don't overshoot into territory where Rust
        // tick logic would diverge from what the TS display expects.
        const targetTick = Math.min(msg.payload.targetTick ?? 0, 120);
        const dt = 1 / 20;
        while (host.tick_count() < targetTick) {
          host.step(dt);
        }
        if (msg.payload.money !== undefined) {
          host.set_money(msg.payload.money);
        }
      }
      // The preloaded save is the undo floor — bulk-replayed history must
      // never be reachable by undo.
      host.clear_history();
      self.postMessage({ type: 'ready', history: historyFlags(host) });
      break;
    }
    case 'step': {
      if (!host) break;
      host.step(msg.payload.dt);
      const bytes = host.tile_buffer();
      const stats = gatherStats(host);
      self.postMessage({ type: 'step_result', bytes, stats }, { transfer: [bytes.buffer as ArrayBuffer] });
      break;
    }
    case 'apply_tool': {
      if (!host) break;
      const success = host.apply_tool(msg.payload.tool, msg.payload.x, msg.payload.y, msg.payload.strokeId);
      self.postMessage({ type: 'apply_result', success, history: historyFlags(host) });
      break;
    }
    case 'set_speed': {
      if (!host) break;
      host.set_speed(msg.payload.multiplier);
      break;
    }
    case 'set_policies': {
      if (!host) break;
      applyPolicies(host, msg.payload);
      break;
    }
    case 'undo': {
      if (!host) break;
      const happened = host.undo();
      if (happened) {
        const bytes = host.tile_buffer();
        const stats = gatherStats(host);
        self.postMessage(
          { type: 'undo_result', happened: true, bytes, stats, history: historyFlags(host) },
          { transfer: [bytes.buffer as ArrayBuffer] },
        );
      } else {
        self.postMessage({ type: 'undo_result', happened: false, history: historyFlags(host) });
      }
      break;
    }
    case 'redo': {
      if (!host) break;
      const happened = host.redo();
      if (happened) {
        const bytes = host.tile_buffer();
        const stats = gatherStats(host);
        self.postMessage(
          { type: 'redo_result', happened: true, bytes, stats, history: historyFlags(host) },
          { transfer: [bytes.buffer as ArrayBuffer] },
        );
      } else {
        self.postMessage({ type: 'redo_result', happened: false, history: historyFlags(host) });
      }
      break;
    }
    case 'reset': {
      host = new SimHost(msg.payload.width, msg.payload.height, msg.payload.seed);
      if (msg.payload.terrain) host.set_natural_terrain(msg.payload.terrain);
      break;
    }
    case 'load': {
      if (!host) break;
      host = new SimHost(msg.payload.width, msg.payload.height, msg.payload.seed);
      if (msg.payload.terrain) host.set_natural_terrain(msg.payload.terrain);
      if (msg.payload.policies) applyPolicies(host, msg.payload.policies);
      if (msg.payload.commands?.length) {
        for (const cmd of msg.payload.commands) {
          host.apply_tool(cmd.tool, cmd.x, cmd.y, 0);
        }
        // Match init: cap fast-forward at 120 ticks to avoid overshooting early saves.
        const targetTick = Math.min(msg.payload.targetTick ?? 120, 120);
        const dt = 1 / 20;
        while (host.tick_count() < targetTick) host.step(dt);
      }
      if (msg.payload.money !== undefined) host.set_money(msg.payload.money);
      // The loaded save is the undo floor — see 'init'.
      host.clear_history();
      const bytes = host.tile_buffer();
      const stats = gatherStats(host);
      self.postMessage({ type: 'step_result', bytes, stats }, { transfer: [bytes.buffer as ArrayBuffer] });
      break;
    }
  }
};
