// Web Worker that hosts the WASM SimHost for the WasmSimBridge.
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: MIT

/**
 * wasmSim.worker.ts — Web Worker that owns the WASM SimHost.
 *
 * Protocol (both directions use structured-clone via postMessage):
 *
 * Main → Worker:
 *   { type: 'init';       payload: { width: number; height: number; seed: number } }
 *   { type: 'step';       payload: { dt: number } }
 *   { type: 'apply_tool'; payload: { tool: number; x: number; y: number } }
 *   { type: 'set_speed';  payload: { multiplier: number } }
 *   { type: 'undo' }
 *   { type: 'reset';      payload: { width: number; height: number; seed: number } }
 *
 * Worker → Main:
 *   { type: 'ready' }
 *   { type: 'step_result';  bytes: Uint8Array; stats: SimStats }  (buffer transferred)
 *   { type: 'apply_result'; success: boolean }
 *   { type: 'undo_result';  happened: false }
 *   { type: 'undo_result';  happened: true; bytes: Uint8Array; stats: SimStats }
 */
// Generated by wasm-pack; run `bun run build:wasm` to regenerate.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import init, { SimHost } from '../wasm/sim_wasm/sim_wasm.js';

export interface SimStats {
  tick: number;
  day: number;
  money: number;
  population: number;
  jobs: number;
  powerBalance: number;
  powerProduced: number;
  powerUsed: number;
  waterBalance: number;
  waterProduced: number;
  waterUsed: number;
  demandResidential: number;
  demandCommercial: number;
  demandIndustrial: number;
  budgetNetPerDay: number;
}

type MainToWorker =
  | { type: 'init';       payload: { width: number; height: number; seed: number; commands?: { tool: number; x: number; y: number }[]; money?: number } }
  | { type: 'step';       payload: { dt: number } }
  | { type: 'apply_tool'; payload: { tool: number; x: number; y: number } }
  | { type: 'set_speed';  payload: { multiplier: number } }
  | { type: 'undo' }
  | { type: 'reset';      payload: { width: number; height: number; seed: number } };

let host: SimHost | null = null;

function gatherStats(h: SimHost): SimStats {
  return {
    tick:               h.tick_count(),
    day:                h.day(),
    money:              h.money(),
    population:         h.population(),
    jobs:               h.jobs(),
    powerBalance:       h.power_balance(),
    powerProduced:      h.power_produced(),
    powerUsed:          h.power_used(),
    waterBalance:       h.water_balance(),
    waterProduced:      h.water_produced(),
    waterUsed:          h.water_used(),
    demandResidential:  h.demand_residential(),
    demandCommercial:   h.demand_commercial(),
    demandIndustrial:   h.demand_industrial(),
    budgetNetPerDay:    h.budget_net_per_day(),
  };
}

self.onmessage = async (e: MessageEvent<MainToWorker>) => {
  const msg = e.data;
  switch (msg.type) {
    case 'init': {
      await init();
      host = new SimHost(msg.payload.width, msg.payload.height, msg.payload.seed);
      if (msg.payload.commands) {
        for (const cmd of msg.payload.commands) {
          host.apply_tool(cmd.tool, cmd.x, cmd.y);
        }
        if (msg.payload.money !== undefined) {
          host.set_money(msg.payload.money);
        }
      }
      self.postMessage({ type: 'ready' });
      break;
    }
    case 'step': {
      if (!host) break;
      host.step(msg.payload.dt);
      const bytes = host.tile_buffer();
      const stats = gatherStats(host);
      self.postMessage({ type: 'step_result', bytes, stats }, { transfer: [bytes.buffer as ArrayBuffer] });
      break;
    }
    case 'apply_tool': {
      if (!host) break;
      const success = host.apply_tool(msg.payload.tool, msg.payload.x, msg.payload.y);
      self.postMessage({ type: 'apply_result', success });
      break;
    }
    case 'set_speed': {
      if (!host) break;
      host.set_speed(msg.payload.multiplier);
      break;
    }
    case 'undo': {
      if (!host) break;
      const happened = host.undo_last();
      if (happened) {
        const bytes = host.tile_buffer();
        const stats = gatherStats(host);
        self.postMessage(
          { type: 'undo_result', happened: true, bytes, stats },
          { transfer: [bytes.buffer as ArrayBuffer] },
        );
      } else {
        self.postMessage({ type: 'undo_result', happened: false });
      }
      break;
    }
    case 'reset': {
      host = new SimHost(msg.payload.width, msg.payload.height, msg.payload.seed);
      break;
    }
  }
};
